http:
  port: 5000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  users:
    host: "*"
    paths: ['/api/v1/user','/api/v1/user/*']
  currency:
    host: "*"
    paths: ['/api/v1/currency','/api/v1/currency/*']
  wallets:
    host: "*"
    paths: ['/api/v1/wallet','/api/v1/wallet/*']
  transferences:
    host: "*"
    paths: ['/api/v1/transference','/api/v1/transference/*']
serviceEndpoints:
  userService:
    url: 'http://104.131.25.80:5001'
  currencyService:
    url: 'http://104.131.25.80:5000'
  walletsService:
    url: 'http://104.131.25.80:5002'
  transferencesService:
    url: 'http://104.131.25.80:5003'
policies:
  - proxy
pipelines:
  userPipeline:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService 
              changeOrigin: true
  currencyPipeline:
    apiEndpoints:
      - currency
    policies:
      - proxy:
          - action:
              serviceEndpoint: currencyService
              changeOrigin: true
  walletsPipeline:
    apiEndpoints:
      - wallets
    policies:
      - proxy:
          - action:
              serviceEndpoint: walletsService
              changeOrigin: true
  transferencesPipeline:
    apiEndpoints:
      - transferences
    policies:
      - proxy:
          - action:
              serviceEndpoint: transferencesService
              changeOrigin: true
